version: '3.7'

services:
  service:
    container_name: service
    build:
      # dockerfile: ./service/Dockerfile
      context: ./service
      target: development
    volumes:
      - .:/usr/service/src/app
      - /usr/service/src/app/node_modules
    ports:
      # - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    # depends_on:
    #   - redis
    #   - postgres
networks:
  webnet:
volumes:
  data: